services:
  keycloak:
    container_name: keycloak-bsnnnn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8889:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"
    volumes:
      - keycloak-data:/opt/keycloak/data

  rabbitmq:
    container_name: rabbitmq-bsnnnnn
    image: rabbitmq:3-management
    ports:
      - "5673:5672"    # RabbitMQ server port
      - "15672:15672"  # RabbitMQ management interface port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - spring-demo
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  spring-demo:
    driver: bridge

volumes:
  keycloak-data:
  rabbitmq-data:

