version: '3.8'

services:
  mysql-service:
    image: mysql:latest
    container_name: mysql-serviceay
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: k1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloakkay
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-service:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: k1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - '8093:8080'
    depends_on:
      mysql-service:
        condition: service_healthy

volumes:
  mysql_data:
