version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-doc
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mongo
      DB_ADDR: mongo
      DB_PORT: 27017
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - "8057:8057"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
